### ISSUE TITLE
Make script for creating dummy devices parametric

### ISSUE THREAD

**Issue by jirihnidek** [LukasMazl/NicSpeedyModule#4]
Please make script for creating dummy devices parametric to be able create various number of dymmy NIC devices. Create also create script for deleting dummy devices.

**Comment by LukasMazl** [comment]
Scripts have been created here:
https://github.com/LukasMazl/NicSpeedyModule/blob/master/scripts/delete_dummy_nic.sh
https://github.com/LukasMazl/NicSpeedyModule/blob/master/scripts/setup_eth.sh
