### ISSUE TITLE
It is not possible to build python c module

### ISSUE THREAD

**Issue by jirihnidek** [LukasMazl/NicSpeedyModule#5]
It is not possible to build module, because:

1. `CMakeLists.txt` expects that `/usr/lib/python3.4/config-3.4m-x86_64-linux-gnu/libpython3.4m.so.1` file exists.
2. `CMakeLists.txt` expects that Python3.7 is installed
3. I guess that some files are missing: `IfNetUtils.c` `IfNetUtils.h` in repository.

**Comment by jirihnidek** [comment]
It is possible to build extension using `python ./setup.py build_ext`, but I wonder why the `CMakeLists.txt` is present?

**Comment by LukasMazl** [comment]
Problem is fixed now
